FROM node:18-alpine

WORKDIR /app
COPY package*.json ./

RUN npm install --only=production

COPY . .

EXPOSE 8081

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001

RUN chown -R nodejs:nodejs /app
USER nodejs


HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD node -e "require('http').get('http://localhost:8081/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })" || exit 1


CMD ["npm", "start"]
